version: '3.7'

services:
  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    image: ghcr.io/mlexchange/mlex_data_clinic:master
    volumes:
      - $READ_DIR:/app/work/data
      - $WRITE_DIR:/app/work/mlex_store
    environment:
      READ_DIR_MOUNT: "${READ_DIR}"
      WRITE_DIR_MOUNT: "${WRITE_DIR}"
      READ_DIR: "/app/work/data"
      WRITE_DIR: "/app/work/mlex_store"
      MLEX_COMPUTE_URL: "${MLEX_COMPUTE_URL}"
      MLEX_CONTENT_URL: "${MLEX_CONTENT_URL}"
      HOST_NICKNAME: "local"
      TILED_KEY: "${TILED_KEY}"
      DEFAULT_TILED_URI: "${DEFAULT_TILED_URI}"
    ports:
      - 127.0.0.1:8072:8050
    networks:
      - computing_api_default

  autoencoders:
    image: ghcr.io/mlexchange/mlex_pytorch_autoencoders:main

networks:
  computing_api_default:
    external: true
