version: "3"

services:
  front-end:
    restart: "unless-stopped"
    container_name: "data_clinic_test"
    build:
      context: "."
      dockerfile: "docker/Dockerfile"
    environment:
      DATA_DIR: "${PWD}/data"
      HOST_NICKNAME: "local"
    volumes:
      - ${PWD}:/app/work
    ports:
      - "8072:8072"
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true
