version: "3"

services:
  front-end:
    restart: "unless-stopped"
    container_name: "data_clinic"
    build:
      context: "."
      dockerfile: "docker/Dockerfile"
    command: "python src/frontend.py"
    environment:
      DATA_DIR: "${PWD}/data"
    volumes:
      - ${PWD}:/app/work
    ports:
      - "8072:8072"
    networks:
      - computing_api_default

networks:
  computing_api_default:
    external: true
