#FROM kumatea/pytorch:latest
FROM sonoisa/deep-learning-coding:pytorch1.6.0_tensorflow2.3.0
USER root
COPY docker/requirements_arm64.txt requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential\
         libsm6 \
         libxext6 \
         libxrender-dev \
         ffmpeg  \
         tree \
         graphviz \
    python3-pip &&\
    pip install --upgrade pip

RUN pip install -r requirements.txt

WORKDIR /app/work/
COPY src/ src/
COPY entrypoint.sh entrypoint.sh

#ENTRYPOINT ["entrypoint.sh"]
CMD ["bash"]
